---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    net: lsio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - FILE__URL=/run/docker-swag/url
      - VALIDATION=http
      - FILE__SUBDOMAINS=/run/docker-swag/subdomains #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - FILE__DUCKDNSTOKEN=/run/docker-swag/duckdnstoken #optional
      - FILE__EMAIL=/run/docker-swag/email #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ${NGINX_CONFIG}:/config
      - ${DOCKERSWAG_CONFIG}:/run/docker-swag
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
